export const catchAsyncError=()=>{
    regturn(req,res)
}